FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --no-optional --silent

COPY . .

RUN npm run build

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh

EXPOSE 5050

CMD ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
